name: Test, Build, and Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests for All Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js for Node.js app
      - name: Set up Node.js for Node.js app
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Install dependencies for Node.js app
      - name: Install Node.js app dependencies
        working-directory: backend
        run: npm install

      # Run tests for Node.js app
      - name: Run Node.js app tests
        working-directory: backend
        run: npm test

      # Set up Node.js for React app
      - name: Set up Node.js for React app
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Install dependencies for React app
      - name: Install React app dependencies
        working-directory: frontend
        run: npm install

      # Run tests for React app
      - name: Run React app tests
        working-directory: frontend
        run: npm test

  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and Push Node.js App
      - name: Build & Push Node.js App
        working-directory: backend
        run: |
          docker build -t olamyde/backend-app:latest .
          docker push olamyde/backend-app:latest

      # Build and Push React.js App
      - name: Build & Push React.js App
        working-directory: frontend
        run: |
          docker build -t olamyde/frontend-app:latest .
          docker push olamyde/frontend-app:latest

  # deploy:
  #   name: Deploy to Kubernetes
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up kubectl
  #       uses: azure/setup-kubectl@v3
  #       with:
  #         version: 'latest'

  #     - name: Configure kubeconfig
  #       run: |
  #         echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
  #         export KUBECONFIG=kubeconfig

  #     # Deploy Node.js App to Kubernetes
  #     - name: Deploy Node.js App
  #       run: kubectl apply -f k8s/backend-deployment.yaml

  #     # Deploy React.js App to Kubernetes
  #     - name: Deploy React.js App
  #       run: kubectl apply -f k8s/frontend-deployment.yaml
