name: Test, Build, and Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests for All Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Install and Test Node.js App
      - name: Install Node.js dependencies
        working-directory: backend
        run: npm ci

      # - name: Run Node.js tests
      #   working-directory: backend
      #   run: npm test

      # Install and Test React App
      - name: Install React dependencies
        working-directory: frontend
        run: npm ci

      # - name: Run React tests
      #   working-directory: frontend
      #   run: npm test

  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and Push Backend (Node.js) Image
      - name: Build & Push Backend Image
        working-directory: backend
        run: |
          docker build -t olamyde/backend-app:latest .
          docker push olamyde/backend-app:latest

      # Build and Push Frontend (React) Image
      - name: Build & Push Frontend Image
        working-directory: frontend
        run: |
          docker build -t olamyde/frontend-app:latest .
          docker push olamyde/frontend-app:latest

  # Uncomment to Enable Kubernetes Deployment
  # deploy:
  #   name: Deploy to Kubernetes
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up kubectl
  #       uses: azure/setup-kubectl@v3
  #       with:
  #         version: 'latest'

  #     - name: Configure kubeconfig
  #       run: |
  #         echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
  #         export KUBECONFIG=kubeconfig

  #     - name: Deploy Backend App
  #       run: kubectl apply -f k8s/backend-deployment.yaml

  #     - name: Deploy Frontend App
  #       run: kubectl apply -f k8s/frontend-deployment.yaml
